"""empty message

Revision ID: 50b0d2e957db
Revises: 
Create Date: 2022-08-08 15:51:33.102124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b0d2e957db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charName', sa.String(length=120), nullable=False),
    sa.Column('charBirthYear', sa.String(length=15), nullable=True),
    sa.Column('charGender', sa.String(length=15), nullable=True),
    sa.Column('charHairColor', sa.String(length=15), nullable=True),
    sa.Column('charEyeColor', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planetName', sa.String(length=120), nullable=False),
    sa.Column('planetClimate', sa.String(length=15), nullable=False),
    sa.Column('planetDiameter', sa.Integer(), nullable=False),
    sa.Column('planetPopulation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargoCapacity', sa.Integer(), nullable=False),
    sa.Column('consumables', sa.Integer(), nullable=False),
    sa.Column('costInCredits', sa.Integer(), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=30), nullable=False),
    sa.Column('maxSpeed', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('charId', sa.Integer(), nullable=True),
    sa.Column('vehicleId', sa.Integer(), nullable=True),
    sa.Column('planetId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charId'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planetId'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicleId'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
