"""empty message

Revision ID: d6ed40f501c1
Revises: 50b0d2e957db
Create Date: 2022-08-08 16:43:41.614596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6ed40f501c1'
down_revision = '50b0d2e957db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('favouritetype', sa.String(length=120), nullable=False),
    sa.Column('favourite_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('hair_color', sa.String(length=120), nullable=False),
    sa.Column('eye_color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicles')
    op.drop_table('characters')
    op.drop_table('favorites')
    op.add_column('planets', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('planets', sa.Column('climate', sa.String(length=15), nullable=False))
    op.add_column('planets', sa.Column('diameter', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('population', sa.Integer(), nullable=False))
    op.drop_column('planets', 'planetClimate')
    op.drop_column('planets', 'planetDiameter')
    op.drop_column('planets', 'planetPopulation')
    op.drop_column('planets', 'planetName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('planetName', mysql.VARCHAR(length=120), nullable=False))
    op.add_column('planets', sa.Column('planetPopulation', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planets', sa.Column('planetDiameter', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planets', sa.Column('planetClimate', mysql.VARCHAR(length=15), nullable=False))
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'climate')
    op.drop_column('planets', 'name')
    op.create_table('favorites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('charId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vehicleId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planetId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['charId'], ['characters.id'], name='favorites_ibfk_1'),
    sa.ForeignKeyConstraint(['planetId'], ['planets.id'], name='favorites_ibfk_2'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='favorites_ibfk_3'),
    sa.ForeignKeyConstraint(['vehicleId'], ['vehicles.id'], name='favorites_ibfk_4'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('charName', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('charBirthYear', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('charGender', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('charHairColor', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('charEyeColor', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vehicles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cargoCapacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumables', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('costInCredits', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crew', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('maxSpeed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('passengers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('people')
    op.drop_table('favourites')
    # ### end Alembic commands ###
